id: custom
base_cfg_path: cfgs/anet_tsp_pdvc.yml

epoch: 1000
caption_decoder_type: standard
pretrain: 'full'
pretrain_path: '/home/james/JA-PDVC/save/custom_v_2024-07-16-11-48-44/model-best.pth'
train_caption_file: '/home/james/JA-PDVC/data/custom/train_anno.json'
val_caption_file: '/home/james/JA-PDVC/data/custom/val_anno.json'
min_epoch_when_save : 10
visual_feature_type: ['tsp']
visual_feature_folder: ['/home/james/JA-PDVC/home/james/JA-PDVC/data/custom']
feature_dim: 512
invalid_video_json: []
train_proposal_file: data/generated_proposals/dbg_trainval_top100.json
eval_proposal_file: data/generated_proposals/dbg_trainval_top100.json
gt_file_for_eval: ['/home/james/JA-PDVC/data/custom/val_anno.json']
gt_file_for_para_eval: ['data/anet/captiondata/para/anet_entities_val_1_para.json', 'data/anet/captiondata/para/anet_entities_val_2_para.json']
criteria_for_best_ckpt: 'dvc'
train_proposal_type: gt
gt_proposal_sample_num: 30
sample_method: nearest

batch_size: 1
lr: 0.00005
learning_rate_decay_start: 200
learning_rate_decay_every: 100
learning_rate_decay_rate: 0.5
weight_decay: 0.0001
save_all_checkpoint: 0

num_queries: 10
dec_layers: 2
enc_layers: 2
transformer_ff_dim: 512
transformer_dropout_prob: 0.1
frame_embedding_num: 100

with_box_refine: 1

fix_xcw: 1
set_cost_caption: 0
set_cost_giou: 4
set_cost_bbox: 0
set_cost_class: 2
#cost_alpha: 0.5
#cost_gamma: 1
#focal_alpha: 0.5
#focal_gamma: 1
caption_loss_coef: 2
giou_loss_coef: 4
bbox_loss_coef: 0
cls_loss_coef: 2
count_loss_coef: 0.5
max_eseq_length: 10
lloss_cross_entropy: 0
lloss_focal_loss: 0
lloss_gau_mask: 1


cap_nheads: 1
cap_dec_n_points: 4
cap_num_feature_levels: 4
soft_attention: 1
att_hid_size: 512

ec_alpha: 1.0
